spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/admin-pay?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: vW6RnHjWMqvktS5H
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  mail:
    host: smtp.qq.com
    port: 465
    username: 410515742@qq.com
    password: sdxgfdlewviubigc
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

file:
  upload-dir: ./files

epay:
  notifyUrl: http://127.0.0.1:8080/pay/order/notify
